### ISSUE TITLE
UI and content roadmap correction

### ISSUE THREAD

**Issue by marchufschmitt** [InseeFrLab/onyxia-web#229]
### Login et register :

- [x] Change text size of alert - body 1 to subtitle 2 (https://www.figma.com/file/vYJVgJU2OZQ96MkhRwNlMZ/NEW-UI-V2?node-id=1875%3A58)
- [x] Style tooltips (Midnight blue color and change padding top: 4px)
- [x] change text size of help texte and label (vérifier caption)
- [x] Add long help text for the field Username - alphanumerique characters (see in Figma model: https://www.figma.com/file/vYJVgJU2OZQ96MkhRwNlMZ/NEW-UI-V2?node-id=2067%3A180)

<img width="631" alt="Capture d’écran 2021-05-03 à 13 35 01" src="https://user-images.githubusercontent.com/62331119/116871342-65130200-ac14-11eb-9f12-001fb91824ba.png">

- [x] Change molecule button disabled surface : #C9C9C9
- [x] Button height : 32px to 36px

### My secrets :

- [x] Add icon copy to the button "Use in a service" and change the text "use in services" to "use in a service"
- [x] Add style and change text to the dialog component when the user click on the button "Use in a service" (see in Figma model : https://www.figma.com/file/vYJVgJU2OZQ96MkhRwNlMZ/NEW-UI-V2?node-id=451%3A27296)

<img width="736" alt="Capture d’écran 2021-05-03 à 13 39 31" src="https://user-images.githubusercontent.com/62331119/116871779-16199c80-ac15-11eb-8a37-4b1798d4eaaf.png">

- [x] Add dialog component when the user delete a secret or a folder (same page in figma model)
- [ ] Validate variable edit when user click on other point on the page
- [ ] Change subtitle text on the page header  : 1) Store, secure and manage your access to tokens, passwords and use them as environment variables. 2) To learn more about generating secrets, see our documentation. ("Stockez, sécurisez et gérer votre accès aux jetons, mots de passe et utilisez-les sous forme de variables d'environnement. 2) Pour en savoir plus sur la génération de secrets, consultez notre documentation.") and update video URL Link to the documentation page ([https://docs.sspcloud.fr/onyxia-guide-avance/utiliser-des-variables-denvironnement](https://docs.sspcloud.fr/onyxia-guide-avance/utiliser-des-variables-denvironnement))

### My account :

- [x] Change Copy icon
- [ ] Remove tooltip on page header
- [x] Change default color tab on dark mode with a custom theme: Midnight blue (see in Figma model here : https://www.figma.com/file/vYJVgJU2OZQ96MkhRwNlMZ/NEW-UI-V2?node-id=2186%3A18)

<img width="995" alt="Capture d’écran 2021-05-03 à 13 41 43" src="https://user-images.githubusercontent.com/62331119/116871941-58db7480-ac15-11eb-962b-8b23c43041d3.png">

- [x] Add two tooltips (see in the same Figma page)

> Text content changes

- [x] Turn title page "Account" to "My account" and the french translation "Mon Compte" to "Mon compte (without uppercase)
- [x] Little modification of the page header subtitle : (remove strong text for "jeton d'acces personnel") and change text "Configure your usernames, emails, passwords and personal access tokens directly connected to your services." (Configurez vos identifiants, e-mails, mots de passe et jetons d'accès personnels directement connectés à vos services.)
- [x] Edit password text link : "Account password" to "Change account password"  (Modifier le mot de passe du compte)
- [x] Change auth information subtitle text : "These informations allows you to identify yourself within the platform and the various services." (Ces informations vous permettent de vous identifier au sein de la plateforme et des différents services.)
- [x] Change services password subtitle text : "This password is required to log in to all of your services. It is generated automatically and renews itself regularly." (Ce mot de passe est nécessaire pour vous connecter à tous vos services. Il est généré automatiquement et se renouvelle régulièrement.)
- [x] Correct an orthograph error in french translation "Adresse IP"
- [x] Change Git contributions subtitle text: "To ensure that you appear from your services as the author of Git contributions" (Pour vous assurez que vous apparaissiez depuis vos services comme l'auteur des contributions Git)
- [x] Change Github and Kaggle token title text: "Connect your Github and Kaggle accounts" (Connecter vos comptes Github et Kaggle)
- [x] Change Github and Kaggle token subtitle text: "Connect your services to external accounts using personal access tokens and environment variables" (Connectez vos services à des comptes extérieurs à l'aide de jetons d'accès personnel et de variables d'environnement)
- [ ] Add Gitlab personal acces token
- [x] Change data informations title text : "Connect your data to your services" (Connecter vos données à vos services)
- [x] Change data informations subtitle text : "Amazon-compatible MinIO object storage (AWS S3). This information is already filled in automatically and is valid until ..." (Stockage object MinIO compatible Amazon (AWS S3). Ces informations sont déjà renseignés automatiquement et sont valide jusqu’à...)
- [x] Change second data informations title text : "To access your storage outside the datalab" (Pour accèder au stockage en dehors du datalab)
- [x] Change second data informations subtitle text : "Download or copy the init script in the programming language of your choice." (Téléchargez ou copiez le script d'initialisation dans le langage de programmation de votre choix.)
- [ ] Add subtitle text content to interface prefrences + change english title text (Configure interface mode) : 1) Enable dark mode : "Low light interface theme with dark colored background." (Thème de l’interface à faible luminosité avec un fond de couleur sombre.) 2) "For advanced platform configurations and features." (Pour des configurations et fonctionnalités avancées de la plateforme.)

### Leftbar navigation

- [x] Change home icon
- [x] Change trainings icon
- [x] Change the name of the english text for the collapse action : "Collapse" to "reduce"
- [x] Change catalog text name : Services catalog (Catalogue de services)
- [x] Add a bigger right margin: spacing(2) to spacing(4)
- [x] Add section divider (see in the model)

<img width="438" alt="Capture d’écran 2021-05-03 à 13 45 22" src="https://user-images.githubusercontent.com/62331119/116872269-e28b4200-ac15-11eb-80e9-5732327b96f1.png">

### Page d'accueil

- [x] Edit and add good button link : 1) Login button : when user isn't log, go to login page, when the user is logged : "Discover datalab" button go to the documentation page) 2) "Consult the catalog" go to services catalog pages 3) "join the community" button go to the tchap canal and 4) "consult data" go to My files page

### Services catalog page

- [x] Correct an orthograph error in french translation on the page header title "quelques"
- [x] And change englsih page header title : "Explore, launch and configure services with just a few clicks."
- [ ] Change : (Déployer facilement des services en suivant notre documentation) et contribuer au catalogue en suivant notre guide de contribution" and link to the documentation page ([https://docs.sspcloud.fr/onyxia-guide-de-demarrage/lancer-un-service](https://docs.sspcloud.fr/onyxia-guide-de-demarrage/lancer-un-service)) (see in the model) 
- [x] Add a new button on the card : "Official website" (Site web officiel")
- [x] Add new tertiary button theme (https://www.figma.com/file/vYJVgJU2OZQ96MkhRwNlMZ/NEW-UI-V2?node-id=124%3A8570)
- [x] Add services list bottom padding (spacing(7))
- [ ] Custom and polish card drop shadow

**Comment by marchufschmitt** [comment]
Change Account icon too in the leftbar navigation

**Comment by marchufschmitt** [comment]
Add tooltip icon next to the text "Resolved value"

**Comment by marchufschmitt** [comment]
Add function "use in a service" when user select a folder with multiple secrets

**Comment by fcomte** [comment]
too old issue :)
